services:
  yarnalternatives:
    image: yarnalternatives
    build:
      context: .
      dockerfile: Presentation/YarnAlternatives/Dockerfile
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongo-data: